const MULTICAST_ADDRESS = '224.0.0.50'
const SERVER_PORT = 9898
const DISCOVERY_PORT = 4321
const AQARA_IV = Buffer.from([0x17, 0x99, 0x6d, 0x09, 0x3d, 0x28, 0xdd, 0xb3, 0xba, 0x69, 0x5a, 0x2e, 0x6f, 0x58, 0x56, 0x2e])

const SUBDEVICE_MIN_VOLT = 2725
const SUBDEVICE_MAX_VOLT = 3100

const GATEWAY_HEARTBEAT_INTERVAL_MS = 10 * 1000
const GATEWAY_HEARTBEAT_OFFLINE_RATIO = 6.5

const SUBDEVICE_BATTERY_HEARTBEAT_INTERVAL_MS = 60 * 60 * 1000
const SUBDEVICE_BATTERY_HEARTBEAT_OFFLINE_RATIO = 2.5

const SUBDEVICE_MAINS_HEARTBEAT_INTERVAL_MS = 10 * 60 * 1000
const SUBDEVICE_MAINS_HEARTBEAT_OFFLINE_RATIO = 2.5

module.exports = {
  MULTICAST_ADDRESS,
  SERVER_PORT,
  DISCOVERY_PORT,
  AQARA_IV,
  SUBDEVICE_MIN_VOLT,
  SUBDEVICE_MAX_VOLT,
  GATEWAY_HEARTBEAT_INTERVAL_MS,
  GATEWAY_HEARTBEAT_OFFLINE_RATIO,
  SUBDEVICE_BATTERY_HEARTBEAT_INTERVAL_MS,
  SUBDEVICE_BATTERY_HEARTBEAT_OFFLINE_RATIO,
  SUBDEVICE_MAINS_HEARTBEAT_INTERVAL_MS,
  SUBDEVICE_MAINS_HEARTBEAT_OFFLINE_RATIO
}
